name: Lint Fix

on:
  schedule:
    - cron: "0 2 * * 0-6"
  workflow_dispatch:

jobs:
  fix-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.4.0
        with:
          args: "--aosp"
          skipCommit: true
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style(core): Format java code'
